/*
Tracks the daily revenue generated by campaigns.
SELECT Campaign.Name, RevenueDate, SUM(Amount) FROM RevenueEntries JOIN Campaigns ON RevenueEntries.CampaignId = Campaigns.Id WHERE RevenueDate BETWEEN @StartDate AND @EndDate GROUP BY Campaign.Name, RevenueDate
*/
namespace ArtistInsightTool.Apps.Views;

public class CampaignRevenueImpactLineChartView(DateTime startDate, DateTime endDate) : ViewBase
{
    public override object Build()
    {
        var factory = UseService<ArtistInsightToolContextFactory>();
        var chart = UseState<object?>((object?)null);
        var exception = UseState<Exception?>((Exception?)null);

        this.UseEffect(async () =>
        {
            try
            {
                var db = factory.CreateDbContext();
                var data = await db.RevenueEntries
                    .Where(re => re.RevenueDate >= startDate && re.RevenueDate <= endDate)
                    .GroupBy(re => new { re.Campaign!.Name, Date = re.RevenueDate.Date })
                    .Select(g => new
                    {
                        CampaignName = g.Key.Name,
                        Date = g.Key.Date.ToString("d MMM"),
                        TotalRevenue = g.Sum(re => (double)re.Amount)
                    })
                    .ToListAsync();

                chart.Set(data.ToLineChart(
                    e => e.Date,
                    [e => e.Sum(f => f.TotalRevenue)],
                    LineChartStyles.Dashboard
                ));
            }
            catch (Exception ex)
            {
                exception.Set(ex);
            }
        }, []);

        var card = new Card().Title("Campaign Revenue Impact").Height(Size.Units(80));

        if (exception.Value != null)
        {
            return card | new ErrorTeaserView(exception.Value);
        }

        if (chart.Value == null)
        {
            return card | new Skeleton();
        }

        return card | chart.Value;
    }
}