/*
The total revenue generated by all artists during the selected date range.
SUM(RevenueEntry.Amount WHERE RevenueEntry.RevenueDate BETWEEN StartDate AND EndDate)
*/
namespace ArtistInsightTool.Apps.Views;

using ArtistInsightTool.Apps.Services;

public class TotalRevenueMetricView(DateTime fromDate, DateTime toDate) : ViewBase
{
  public override object Build()
  {
    var service = UseService<ArtistInsightService>();

    async Task<MetricRecord> CalculateTotalRevenue()
    {
      var dto = await service.GetTotalRevenueAsync(fromDate, toDate);
      return dto != null ? new MetricRecord(
          MetricFormatted: dto.Value,
          TrendComparedToPreviousPeriod: dto.Trend,
          GoalAchieved: dto.GoalProgress,
          GoalFormatted: dto.GoalValue
      ) : new MetricRecord("0", null, null, null);
    }

    return new MetricView(
        "Total Revenue",
        Icons.DollarSign,
        CalculateTotalRevenue
    );
  }
}