// <auto-generated />
using System;
using ArtistInsightTool.Connections.ArtistInsightTool;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtistInsightTool.Migrations
{
    [DbContext(typeof(ArtistInsightToolContext))]
    [Migration("20260115205717_AddAssetRevenue")]
    partial class AddAssetRevenue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ArtistId" }, "IX_albums_ArtistId");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountGenerated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.AssetRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevenueEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RevenueEntryId");

                    b.ToTable("asset_revenues");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.EfmigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.ImportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmountColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetColumn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportTemplates");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Integration")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RevenueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AlbumId" }, "IX_revenue_entries_AlbumId");

                    b.HasIndex(new[] { "ArtistId" }, "IX_revenue_entries_ArtistId");

                    b.HasIndex(new[] { "SourceId" }, "IX_revenue_entries_SourceId");

                    b.HasIndex(new[] { "TrackId" }, "IX_revenue_entries_TrackId");

                    b.ToTable("revenue_entries");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("revenue_sources");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AlbumId" }, "IX_tracks_AlbumId");

                    b.HasIndex(new[] { "ArtistId" }, "IX_tracks_ArtistId");

                    b.ToTable("tracks");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Album", b =>
                {
                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.AssetRevenue", b =>
                {
                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", "RevenueEntry")
                        .WithMany()
                        .HasForeignKey("RevenueEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("RevenueEntry");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", b =>
                {
                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Album", "Album")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Artist", "Artist")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.RevenueSource", "Source")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Track", "Track")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Album");

                    b.Navigation("Artist");

                    b.Navigation("Source");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Track", b =>
                {
                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Album", b =>
                {
                    b.Navigation("RevenueEntries");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Artist", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("RevenueEntries");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueSource", b =>
                {
                    b.Navigation("RevenueEntries");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Track", b =>
                {
                    b.Navigation("RevenueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
