// <auto-generated />
using System;
using ArtistInsightTool.Connections.ArtistInsightTool;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtistInsightTool.Migrations
{
    [DbContext(typeof(ArtistInsightToolContext))]
    [Migration("20260127141228_AddSourceNameToImportTemplate")]
    partial class AddSourceNameToImportTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountGenerated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.AssetRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevenueEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RevenueEntryId");

                    b.ToTable("asset_revenues");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.EfmigrationsLock", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("__EFMigrationsLock");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.ImportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmountColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetTypeColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionColumn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmailColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DspColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventStatusColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrossColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsrcColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuantityColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkuColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePlatformColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerritoryColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketClassColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionDateColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionIdColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpcColumn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueNameColumn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("import_templates");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnMapping")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Integration")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RevenueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportTemplateId");

                    b.HasIndex(new[] { "ArtistId" }, "IX_revenue_entries_ArtistId");

                    b.HasIndex(new[] { "SourceId" }, "IX_revenue_entries_SourceId");

                    b.ToTable("revenue_entries");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("revenue_sources");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.AssetRevenue", b =>
                {
                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Asset", "Asset")
                        .WithMany("AssetRevenues")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", "RevenueEntry")
                        .WithMany("AssetRevenues")
                        .HasForeignKey("RevenueEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("RevenueEntry");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", b =>
                {
                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.Artist", "Artist")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.ImportTemplate", "ImportTemplate")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("ImportTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArtistInsightTool.Connections.ArtistInsightTool.RevenueSource", "Source")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("ImportTemplate");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Artist", b =>
                {
                    b.Navigation("RevenueEntries");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.Asset", b =>
                {
                    b.Navigation("AssetRevenues");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.ImportTemplate", b =>
                {
                    b.Navigation("RevenueEntries");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueEntry", b =>
                {
                    b.Navigation("AssetRevenues");
                });

            modelBuilder.Entity("ArtistInsightTool.Connections.ArtistInsightTool.RevenueSource", b =>
                {
                    b.Navigation("RevenueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
