// <auto-generated />
using System;
using ArtistInsight.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtistInsight.Backend.Migrations
{
    [DbContext(typeof(ArtistInsightContext))]
    [Migration("20260120130228_AllowDeleteTemplate")]
    partial class AllowDeleteTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ArtistInsight.Backend.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("artists");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountGenerated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.AssetRevenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevenueEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RevenueEntryId");

                    b.ToTable("asset_revenues");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.ImportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmountColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtistColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionColumn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DspColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrossColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreColumn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TerritoryColumn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("import_templates");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.RevenueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColumnMapping")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImportTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Integration")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RevenueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("ImportTemplateId");

                    b.HasIndex("SourceId");

                    b.ToTable("revenue_entries");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.RevenueSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("revenue_sources");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.AssetRevenue", b =>
                {
                    b.HasOne("ArtistInsight.Backend.Models.Asset", "Asset")
                        .WithMany("AssetRevenues")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtistInsight.Backend.Models.RevenueEntry", "RevenueEntry")
                        .WithMany("AssetRevenues")
                        .HasForeignKey("RevenueEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("RevenueEntry");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.RevenueEntry", b =>
                {
                    b.HasOne("ArtistInsight.Backend.Models.Artist", "Artist")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArtistInsight.Backend.Models.ImportTemplate", "ImportTemplate")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("ImportTemplateId");

                    b.HasOne("ArtistInsight.Backend.Models.RevenueSource", "Source")
                        .WithMany("RevenueEntries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("ImportTemplate");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.Artist", b =>
                {
                    b.Navigation("RevenueEntries");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.Asset", b =>
                {
                    b.Navigation("AssetRevenues");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.ImportTemplate", b =>
                {
                    b.Navigation("RevenueEntries");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.RevenueEntry", b =>
                {
                    b.Navigation("AssetRevenues");
                });

            modelBuilder.Entity("ArtistInsight.Backend.Models.RevenueSource", b =>
                {
                    b.Navigation("RevenueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
